# Generated by Django 3.0.4 on 2020-03-26 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200327_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_view',
            name='textcontent',
        ),
        migrations.CreateModel(
            name='Blog_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textcontent', models.TextField(default='This blog is under Construction !')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog_view')),
            ],
        ),
    ]
