# Generated by Django 3.0.4 on 2020-03-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200327_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_view',
            name='textcontent',
            field=models.TextField(default='This blog is under Construction !'),
        ),
        migrations.DeleteModel(
            name='Blog_content',
        ),
    ]
